name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: build
        run: gradle clean build 
      - name: run test
        run: gradle clean test
      - name: Publish Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1
